### ISSUE TITLE
Dialog only firing closed event

### ISSUE THREAD

**Issue by bofwant** [IswPolymerElements/isw-dialog#4]
i have this dialog

![image](https://user-images.githubusercontent.com/8497707/39793117-007ec4d6-5312-11e8-9072-b24b76e2d73c.png)

and this is my remote

![image](https://user-images.githubusercontent.com/8497707/39793130-0c1caa88-5312-11e8-8019-0b6bd2225190.png)

but both buttons are firing the closed event.

**Comment by rene-lindner-isw** [comment]
Because both buttons are closing the dialog ;)
The paper-dialog-behavior events are forewarded 1:1 so you can use the paper-dialog documentation.
Do differ the closing reason you have to evaluate the event details.
